import csv, hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D = ROOT / "Data"


def dir_hash(p):
    h = hashlib.sha256()
    for f in sorted(x for x in p.rglob("*") if x.is_file()):
        h.update(f"{f.relative_to(p).as_posix()}:{f.stat().st_size}\n".encode())
    return h.hexdigest()[:16]


def tier(p):
    names = {x.name.lower() for x in p.rglob("*")} if p.is_dir() else {p.name.lower()}
    if "odometry.csv" in names or "depth" in names:
        return "lidar"
    if any(n.endswith((".mp4", ".mov")) for n in names):
        return "video"
    if any(n.endswith((".jpg", ".jpeg", ".png", ".heic")) for n in names):
        return "photo"
    return "other"


rows = []
for p in sorted(D.iterdir()):
    if p.name in ("ground_truth", "app_exports") or p.name.startswith("."):
        continue
    files = [f for f in p.rglob("*") if f.is_file()] if p.is_dir() else [p]
    rows.append((p.name, tier(p), len(files), sum(f.stat().st_size for f in files) / 1e6, dir_hash(p) if p.is_dir() else "-"))

cov = list(csv.DictReader(open(D / "bench_set_coverage.csv", newline="", encoding="utf-8")))
gt = sorted(x.name for x in (D / "ground_truth").glob("*.csv"))
exp = sorted(x.name for x in (D / "app_exports").glob("*"))

out = ["# Raw Benchmark Data Index", "",
       "Generated by `scripts/make_data_index.py`. Large LiDAR captures ship in the separate raw archive "
       "(see MANIFEST_RAW.json).", "",
       "## Benchmark-set coverage (B1-B7)", "", "| Item | Requirement | Status | Evidence | Note |", "|---|---|---|---|---|"]
out += [f"| {c['item']} | {c['requirement']} | {c['status']} | {c['evidence']} | {c['note']} |" for c in cov]
out += ["", "## Captures", "", "| Folder | Tier | Files | MB | Listing hash |", "|---|---|---|---|---|"]
out += [f"| {n} | {t} | {c} | {mb:.1f} | `{h}` |" for n, t, c, mb, h in rows]
out += ["", "Empty folders (e.g. `4BHKVILLA`, `MyApartment`) are listed with 0 files; delete them or fill them before submission.",
        "", "## Ground truth files", ""] + [f"- `{g}`" for g in gt]
out += ["", "## App exports", ""] + ([f"- `{e}`" for e in exp] or ["- none (G9 not measured)"])
(D / "DATA_INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote Data/DATA_INDEX.md")
